version: '3.8'

services:
  quasar:
    build:
      context: ../../
      dockerfile: nunki/helpers/quasar.Dockerfile
    image: nunki/quasar:latest
    container_name: quasar-server
    ports:
      - "4840:4840"
    networks:
      - nunki-network

  nunki:
    build:
      context: ../
      dockerfile: helpers/Dockerfile
    image: nunki/app:latest
    container_name: nunki-app
    ports:
      - "8080:8080"
    environment:
      - QUASAR_OPCUA_URL=opc.tcp://quasar:4840
    depends_on:
      - quasar
    networks:
      - nunki-network

networks:
  nunki-network:
    driver: bridge
