@startsalt
{
  == Time Series Visualizer
  Real-time graph plotted directly via SVG based on WebSocket events
  .
  {^Simulated Sensor Frequency (Hz)                         [20 points cached]^
    {
      100.0 | - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
            |                     . * .
       75.0 | - - - - - - - - - * - - - - * - - - - - - - - - - - - - - - -
            |                 *             *
       50.0 | - - - - - - - * - - - - - - - - - * - - - - - - - - - - - - -
            |             *                       *
       25.0 | - - - - - * - - - - - - - - - - - - - - * - - - - - - - - - -
            |         *                                 *
        0.0 | - - - * - - - - - - - - - - - - - - - - - - - * - - - - - - -
      ======|==============================================================
            | 12:00:01     12:00:05     12:00:10     12:00:15     12:00:20
    }
  }
}
@endsalt
